### ISSUE TITLE
Users in config.yaml

### ISSUE THREAD

**Issue by bugsysop** [leomoon-studios/wiki-go#69]
Question about what’s the correct way to manage users in Wiki-Go config file.

In the demo site, the sample `config.yaml` file suggest:

```
users:
    - username: admin
      password: <bcrypt-hashed-password>
      is_admin: true
```

In the main Wiki-Go Github repo, the `config.yaml` file from `sample-demo-site/` directory show:

```
users:
    - username: admin
      password: <bcrypt-hashed-password>
      role: admin
```
Witch is the correct notation?

I tested the two, and actually the two are working fine...
